import express from "express";
import { usercontorler } from "./user.contorler";
const route = express.Router();
route.post("/", usercontorler.createuser);
route.get("/", usercontorler.getalluser);
route.get("/:userId", usercontorler.getSingleuser);
route.put("/:userId", usercontorler.UpdateSingleuser);
route.delete("/:userId", usercontorler.DeleteSingleuser);
route.put("/:userId/orders", usercontorler.Orderuser);
route.get("/:userId/orders", usercontorler.getSingleuserorder);
route.get("/:userId/orders/total-price", usercontorler.getSingleuserorderTotal);
export const userRoute = route;
